// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

namespace NWN.LowLevel
{
    public unsafe partial class CExoIniInternal : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 8)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal __IntPtr m_pFileNames;

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CExoIniInternalC2E10CExoString", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void ctor(__IntPtr __instance, __IntPtr sUserDirectory);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CExoIniInternalC2ERKS_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void cctor_1(__IntPtr __instance, __IntPtr _0);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CExoIniInternalD2Ev", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void dtor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CExoIniInternal12ReadIniEntryER10CExoStringRKiRKS0_S5_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern int ReadIniEntry(__IntPtr __instance, __IntPtr sValue, int* idxIniFile, __IntPtr sSection, __IntPtr sEntry);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CExoIniInternal13WriteIniEntryERK10CExoStringRKiS2_S2_i", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern int WriteIniEntry(__IntPtr __instance, __IntPtr sValue, int* idxIniFile, __IntPtr sSection, __IntPtr sEntry, int stripIfEmpty);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CExoIniInternal> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CExoIniInternal>();

        protected bool __ownsNativeInstance;

        internal static CExoIniInternal __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            return new CExoIniInternal(native.ToPointer(), skipVTables);
        }

        internal static CExoIniInternal __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (NativeToManagedMap.TryGetValue(native, out var managed))
                return (CExoIniInternal)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                NativeToManagedMap[native] = result;
            return result;
        }

        internal static CExoIniInternal __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new CExoIniInternal(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            *(__Internal*) ret = native;
            return ret.ToPointer();
        }

        private CExoIniInternal(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected CExoIniInternal(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        public CExoIniInternal(global::NWN.LowLevel.CExoString sUserDirectory)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CExoIniInternal.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(sUserDirectory, null))
                throw new global::System.ArgumentNullException("sUserDirectory", "Cannot be null because it is passed by value.");
            var __arg0 = sUserDirectory.__Instance;
            __Internal.ctor(__Instance, __arg0);
        }

        public CExoIniInternal(global::NWN.LowLevel.CExoIniInternal _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CExoIniInternal.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::NWN.LowLevel.CExoIniInternal.__Internal*) __Instance) = *((global::NWN.LowLevel.CExoIniInternal.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::NWN.LowLevel.CExoIniInternal __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (disposing)
                __Internal.dtor(__Instance);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public int ReadIniEntry(global::NWN.LowLevel.CExoString sValue, int idxIniFile, global::NWN.LowLevel.CExoString sSection, global::NWN.LowLevel.CExoString sEntry)
        {
            if (ReferenceEquals(sValue, null))
                throw new global::System.ArgumentNullException("sValue", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = sValue.__Instance;
            var __arg1 = &idxIniFile;
            if (ReferenceEquals(sSection, null))
                throw new global::System.ArgumentNullException("sSection", "Cannot be null because it is a C++ reference (&).");
            var __arg2 = sSection.__Instance;
            if (ReferenceEquals(sEntry, null))
                throw new global::System.ArgumentNullException("sEntry", "Cannot be null because it is a C++ reference (&).");
            var __arg3 = sEntry.__Instance;
            var __ret = __Internal.ReadIniEntry(__Instance, __arg0, __arg1, __arg2, __arg3);
            return __ret;
        }

        public int WriteIniEntry(global::NWN.LowLevel.CExoString sValue, int idxIniFile, global::NWN.LowLevel.CExoString sSection, global::NWN.LowLevel.CExoString sEntry, int stripIfEmpty)
        {
            if (ReferenceEquals(sValue, null))
                throw new global::System.ArgumentNullException("sValue", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = sValue.__Instance;
            var __arg1 = &idxIniFile;
            if (ReferenceEquals(sSection, null))
                throw new global::System.ArgumentNullException("sSection", "Cannot be null because it is a C++ reference (&).");
            var __arg2 = sSection.__Instance;
            if (ReferenceEquals(sEntry, null))
                throw new global::System.ArgumentNullException("sEntry", "Cannot be null because it is a C++ reference (&).");
            var __arg3 = sEntry.__Instance;
            var __ret = __Internal.WriteIniEntry(__Instance, __arg0, __arg1, __arg2, __arg3, stripIfEmpty);
            return __ret;
        }

        public static implicit operator global::NWN.LowLevel.CExoIniInternal(global::NWN.LowLevel.CExoString sUserDirectory)
        {
            return new global::NWN.LowLevel.CExoIniInternal(sUserDirectory);
        }

        public global::NWN.LowLevel.CExoString MPFileNames
        {
            get
            {
                var __result0 = global::NWN.LowLevel.CExoString.__GetOrCreateInstance(((__Internal*)__Instance)->m_pFileNames, false);
                return __result0;
            }

            set
            {
                ((__Internal*)__Instance)->m_pFileNames = value is null ? __IntPtr.Zero : value.__Instance;
            }
        }
    }
}

namespace Std
{
    namespace Pair
    {
        [StructLayout(LayoutKind.Explicit, Size = 80)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__S_CExoString___S_CNWSScriptVar
        {
            [FieldOffset(0)]
            internal global::NWN.LowLevel.CExoString.__Internal first;

            [FieldOffset(16)]
            internal global::NWN.LowLevel.CNWSScriptVar.__Internal second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C___S_CachedRulesetEntry
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::NWN.LowLevel.CachedRulesetEntry.__Internal second;
        }
    }

}
namespace Std
{
    namespace Hashtable
    {
        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S__Hashtable____S_CExoString___N_std_S_pair__1S0____S_CNWSScriptVar___N_std_S_allocator__S1____N_std_N___detail_S__Select1st___N_std_S_equal_to__S0____N_std_S_hash__S0____N_std_N___detail_S__Mod_range_hashing___N_std_N___detail_S__Default_ranged_hash___N_std_N___detail_S__Prime_rehash_policy___N_std_N___detail_S__Hashtable_traits__Vb1_Vb0_Vb1
        {
            [FieldOffset(0)]
            internal __IntPtr _M_buckets;

            [FieldOffset(8)]
            internal ulong _M_bucket_count;

            [FieldOffset(16)]
            internal global::Std.Detail.HashNodeBase.__Internal _M_before_begin;

            [FieldOffset(24)]
            internal ulong _M_element_count;

            [FieldOffset(32)]
            internal global::Std.Detail.PrimeRehashPolicy.__Internal _M_rehash_policy;

            [FieldOffset(48)]
            internal __IntPtr _M_single_bucket;
        }
    }
}
