// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

namespace NWN.LowLevel
{
    public unsafe partial class CItemPropertyApplierRemover : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 8)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal __IntPtr vptr_CItemPropertyApplierRemover;

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN27CItemPropertyApplierRemoverC2Ev", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void ctor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN27CItemPropertyApplierRemoverC2ERKS_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void cctor(__IntPtr __instance, __IntPtr _0);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CItemPropertyApplierRemover> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CItemPropertyApplierRemover>();

        protected bool __ownsNativeInstance;

        internal static CItemPropertyApplierRemover __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            return new CItemPropertyApplierRemover(native.ToPointer(), skipVTables);
        }

        internal static CItemPropertyApplierRemover __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (NativeToManagedMap.TryGetValue(native, out var managed))
                return (CItemPropertyApplierRemover)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                NativeToManagedMap[native] = result;
            return result;
        }

        internal static CItemPropertyApplierRemover __GetInstance(__IntPtr native)
        {
            if (!NativeToManagedMap.TryGetValue(native, out var managed))
                throw new System.Exception("No managed instance was found");
            var result = (CItemPropertyApplierRemover)managed;
            if (result.__ownsNativeInstance)
                result.SetupVTables();
            return result;
        }

        internal static CItemPropertyApplierRemover __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new CItemPropertyApplierRemover(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            global::NWN.LowLevel.CItemPropertyApplierRemover.__Internal.cctor(ret, new __IntPtr(&native));
            return ret.ToPointer();
        }

        private CItemPropertyApplierRemover(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected CItemPropertyApplierRemover(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
            if (!skipVTables)
                SetupVTables(true);
        }

        public CItemPropertyApplierRemover()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CItemPropertyApplierRemover.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor(__Instance);
            SetupVTables(GetType().FullName == "NWN.LowLevel.CItemPropertyApplierRemover");
        }

        public CItemPropertyApplierRemover(global::NWN.LowLevel.CItemPropertyApplierRemover _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CItemPropertyApplierRemover.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(_0, null))
                throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = _0.__Instance;
            __Internal.cctor(__Instance, __arg0);
            SetupVTables(GetType().FullName == "NWN.LowLevel.CItemPropertyApplierRemover");
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::NWN.LowLevel.CItemPropertyApplierRemover __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            ((global::NWN.LowLevel.CItemPropertyApplierRemover.__Internal*) __Instance)->vptr_CItemPropertyApplierRemover = __VTables.Tables[0];
            if (disposing)
            {
                var ___dtorDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr>(0, 0);
                ___dtorDelegate(__Instance);
            }
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public virtual void InitializeItemProperties()
        {
            var ___InitializeItemPropertiesDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr>(0, 2);
            ___InitializeItemPropertiesDelegate(__Instance);
        }

        public virtual int OnItemPropertyApplied(global::NWN.LowLevel.CNWSItem pItem, global::NWN.LowLevel.CNWItemProperty pItemProperty, global::NWN.LowLevel.CNWSCreature pTargetCreature, uint nTargetInventorySlot, int bLoadingGame)
        {
            var ___OnItemPropertyAppliedDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Func_int___IntPtr___IntPtr___IntPtr___IntPtr_uint_int>(0, 3);
            var __arg0 = pItem is null ? __IntPtr.Zero : pItem.__Instance;
            var __arg1 = pItemProperty is null ? __IntPtr.Zero : pItemProperty.__Instance;
            var __arg2 = pTargetCreature is null ? __IntPtr.Zero : pTargetCreature.__Instance;
            var __ret = ___OnItemPropertyAppliedDelegate(__Instance, __arg0, __arg1, __arg2, nTargetInventorySlot, bLoadingGame);
            return __ret;
        }

        public virtual int OnItemPropertyRemoved(global::NWN.LowLevel.CNWSItem pItem, global::NWN.LowLevel.CNWItemProperty pItemProperty, global::NWN.LowLevel.CNWSCreature pTargetCreature, uint nTargetInventorySlot)
        {
            var ___OnItemPropertyRemovedDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Func_int___IntPtr___IntPtr___IntPtr___IntPtr_uint>(0, 4);
            var __arg0 = pItem is null ? __IntPtr.Zero : pItem.__Instance;
            var __arg1 = pItemProperty is null ? __IntPtr.Zero : pItemProperty.__Instance;
            var __arg2 = pTargetCreature is null ? __IntPtr.Zero : pTargetCreature.__Instance;
            var __ret = ___OnItemPropertyRemovedDelegate(__Instance, __arg0, __arg1, __arg2, nTargetInventorySlot);
            return __ret;
        }

        #region Virtual table interop

        // virtual ~CItemPropertyApplierRemover()
        private static global::NWN.LowLevel.Delegates.Action___IntPtr _dtorDelegateInstance;

        private static void _dtorDelegateHook(__IntPtr __instance)
        {
            var __target = global::NWN.LowLevel.CItemPropertyApplierRemover.__GetInstance(__instance);
            __target.Dispose(true);
        }

        // void InitializeItemProperties()
        private static global::NWN.LowLevel.Delegates.Action___IntPtr _InitializeItemPropertiesDelegateInstance;

        private static void _InitializeItemPropertiesDelegateHook(__IntPtr __instance)
        {
            var __target = global::NWN.LowLevel.CItemPropertyApplierRemover.__GetInstance(__instance);
            __target.InitializeItemProperties();
        }

        // int32_t OnItemPropertyApplied(CNWSItem * pItem, CNWItemProperty * pItemProperty, CNWSCreature * pTargetCreature, uint32_t nTargetInventorySlot, BOOL bLoadingGame)
        private static global::NWN.LowLevel.Delegates.Func_int___IntPtr___IntPtr___IntPtr___IntPtr_uint_int _OnItemPropertyAppliedDelegateInstance;

        private static int _OnItemPropertyAppliedDelegateHook(__IntPtr __instance, __IntPtr pItem, __IntPtr pItemProperty, __IntPtr pTargetCreature, uint nTargetInventorySlot, int bLoadingGame)
        {
            var __target = global::NWN.LowLevel.CItemPropertyApplierRemover.__GetInstance(__instance);
            var __result0 = global::NWN.LowLevel.CNWSItem.__GetOrCreateInstance(pItem, false);
            var __result1 = global::NWN.LowLevel.CNWItemProperty.__GetOrCreateInstance(pItemProperty, false);
            var __result2 = global::NWN.LowLevel.CNWSCreature.__GetOrCreateInstance(pTargetCreature, false);
            return __target.OnItemPropertyApplied(__result0, __result1, __result2, nTargetInventorySlot, bLoadingGame);
        }

        // int32_t OnItemPropertyRemoved(CNWSItem * pItem, CNWItemProperty * pItemProperty, CNWSCreature * pTargetCreature, uint32_t nTargetInventorySlot)
        private static global::NWN.LowLevel.Delegates.Func_int___IntPtr___IntPtr___IntPtr___IntPtr_uint _OnItemPropertyRemovedDelegateInstance;

        private static int _OnItemPropertyRemovedDelegateHook(__IntPtr __instance, __IntPtr pItem, __IntPtr pItemProperty, __IntPtr pTargetCreature, uint nTargetInventorySlot)
        {
            var __target = global::NWN.LowLevel.CItemPropertyApplierRemover.__GetInstance(__instance);
            var __result0 = global::NWN.LowLevel.CNWSItem.__GetOrCreateInstance(pItem, false);
            var __result1 = global::NWN.LowLevel.CNWItemProperty.__GetOrCreateInstance(pItemProperty, false);
            var __result2 = global::NWN.LowLevel.CNWSCreature.__GetOrCreateInstance(pTargetCreature, false);
            return __target.OnItemPropertyRemoved(__result0, __result1, __result2, nTargetInventorySlot);
        }

        internal static class VTableLoader
        {
            private static volatile bool initialized;
            private static readonly IntPtr*[] ManagedVTables = new IntPtr*[1];
            private static readonly IntPtr*[] ManagedVTablesDtorOnly = new IntPtr*[1];
            private static readonly IntPtr[] Thunks = new IntPtr[4];
            private static CppSharp.Runtime.VTables VTables;
            private static readonly global::System.Collections.Generic.List<CppSharp.Runtime.SafeUnmanagedMemoryHandle>
                SafeHandles = new global::System.Collections.Generic.List<CppSharp.Runtime.SafeUnmanagedMemoryHandle>();

            static VTableLoader()
            {
                _dtorDelegateInstance += _dtorDelegateHook;
                _InitializeItemPropertiesDelegateInstance += _InitializeItemPropertiesDelegateHook;
                _OnItemPropertyAppliedDelegateInstance += _OnItemPropertyAppliedDelegateHook;
                _OnItemPropertyRemovedDelegateInstance += _OnItemPropertyRemovedDelegateHook;
                Thunks[0] = Marshal.GetFunctionPointerForDelegate(_dtorDelegateInstance);
                Thunks[1] = Marshal.GetFunctionPointerForDelegate(_InitializeItemPropertiesDelegateInstance);
                Thunks[2] = Marshal.GetFunctionPointerForDelegate(_OnItemPropertyAppliedDelegateInstance);
                Thunks[3] = Marshal.GetFunctionPointerForDelegate(_OnItemPropertyRemovedDelegateInstance);
            }

            public static CppSharp.Runtime.VTables SetupVTables(IntPtr instance, bool destructorOnly = false)
            {
                if (!initialized)
                {
                    lock (ManagedVTables)
                    {
                        if (!initialized)
                        {
                            initialized = true;
                            VTables.Tables = new IntPtr[] { *(IntPtr*)(instance + 0) };
                            VTables.Methods = new Delegate[1][];
                            ManagedVTablesDtorOnly[0] = CppSharp.Runtime.VTables.CloneTable(SafeHandles, instance, 0, 7);
                            ManagedVTablesDtorOnly[0][1] = Thunks[0];
                            ManagedVTables[0] = CppSharp.Runtime.VTables.CloneTable(SafeHandles, instance, 0, 7);
                            ManagedVTables[0][1] = Thunks[0];
                            ManagedVTables[0][2] = Thunks[1];
                            ManagedVTables[0][3] = Thunks[2];
                            ManagedVTables[0][4] = Thunks[3];
                            VTables.Methods[0] = new Delegate[7];
                        }
                    }
                }

                if (destructorOnly)
                {
                    *(IntPtr**)(instance + 0) = ManagedVTablesDtorOnly[0];
                }
                else
                {
                    *(IntPtr**)(instance + 0) = ManagedVTables[0];
                }
                return VTables;
            }
        }

        protected CppSharp.Runtime.VTables __vtables;
        internal virtual CppSharp.Runtime.VTables __VTables
        { 
            get {
                if (__vtables.IsEmpty)
                    __vtables.Tables = new IntPtr[] { *(IntPtr*)(__Instance + 0) };
                return __vtables;
            }

            set {        
                __vtables = value;
            }
        }

        internal virtual void SetupVTables(bool destructorOnly = false)
        {
            if (__VTables.IsTransient)
                __VTables = VTableLoader.SetupVTables(__Instance, destructorOnly);
        }
        #endregion
    }
}

namespace Std
{
    namespace Pair
    {
        [StructLayout(LayoutKind.Explicit, Size = 80)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__S_CExoString___S_CNWSScriptVar
        {
            [FieldOffset(0)]
            internal global::NWN.LowLevel.CExoString.__Internal first;

            [FieldOffset(16)]
            internal global::NWN.LowLevel.CNWSScriptVar.__Internal second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C___S_CachedRulesetEntry
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::NWN.LowLevel.CachedRulesetEntry.__Internal second;
        }
    }

}
namespace Std
{
    namespace Hashtable
    {
        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S__Hashtable____S_CExoString___N_std_S_pair__1S0____S_CNWSScriptVar___N_std_S_allocator__S1____N_std_N___detail_S__Select1st___N_std_S_equal_to__S0____N_std_S_hash__S0____N_std_N___detail_S__Mod_range_hashing___N_std_N___detail_S__Default_ranged_hash___N_std_N___detail_S__Prime_rehash_policy___N_std_N___detail_S__Hashtable_traits__Vb1_Vb0_Vb1
        {
            [FieldOffset(0)]
            internal __IntPtr _M_buckets;

            [FieldOffset(8)]
            internal ulong _M_bucket_count;

            [FieldOffset(16)]
            internal global::Std.Detail.HashNodeBase.__Internal _M_before_begin;

            [FieldOffset(24)]
            internal ulong _M_element_count;

            [FieldOffset(32)]
            internal global::Std.Detail.PrimeRehashPolicy.__Internal _M_rehash_policy;

            [FieldOffset(48)]
            internal __IntPtr _M_single_bucket;
        }
    }
}
