// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

namespace NWN.LowLevel
{
    public unsafe partial class CNWAmbientSound : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 48)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal __IntPtr vptr_CNWAmbientSound;

            [FieldOffset(8)]
            internal int m_bMusicPlaying;

            [FieldOffset(12)]
            internal int m_nMusicDelay;

            [FieldOffset(16)]
            internal int m_nMusicDayTrack;

            [FieldOffset(20)]
            internal int m_nMusicNightTrack;

            [FieldOffset(24)]
            internal int m_bBattlePlaying;

            [FieldOffset(28)]
            internal int m_nBattleTrack;

            [FieldOffset(32)]
            internal int m_bSoundPlaying;

            [FieldOffset(36)]
            internal int m_nSoundDayTrack;

            [FieldOffset(40)]
            internal int m_nSoundNightTrack;

            [FieldOffset(44)]
            internal byte m_nDayVolume;

            [FieldOffset(45)]
            internal byte m_nNightVolume;

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CNWAmbientSoundC2Ev", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void ctor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN15CNWAmbientSoundC2ERKS_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void cctor(__IntPtr __instance, __IntPtr _0);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CNWAmbientSound> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CNWAmbientSound>();

        protected bool __ownsNativeInstance;

        internal static CNWAmbientSound __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            return new CNWAmbientSound(native.ToPointer(), skipVTables);
        }

        internal static CNWAmbientSound __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (NativeToManagedMap.TryGetValue(native, out var managed))
                return (CNWAmbientSound)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                NativeToManagedMap[native] = result;
            return result;
        }

        internal static CNWAmbientSound __GetInstance(__IntPtr native)
        {
            if (!NativeToManagedMap.TryGetValue(native, out var managed))
                throw new System.Exception("No managed instance was found");
            var result = (CNWAmbientSound)managed;
            if (result.__ownsNativeInstance)
                result.SetupVTables();
            return result;
        }

        internal static CNWAmbientSound __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new CNWAmbientSound(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            global::NWN.LowLevel.CNWAmbientSound.__Internal.cctor(ret, new __IntPtr(&native));
            return ret.ToPointer();
        }

        private CNWAmbientSound(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected CNWAmbientSound(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        public CNWAmbientSound()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CNWAmbientSound.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor(__Instance);
            SetupVTables(GetType().FullName == "NWN.LowLevel.CNWAmbientSound");
        }

        public CNWAmbientSound(global::NWN.LowLevel.CNWAmbientSound _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CNWAmbientSound.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(_0, null))
                throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = _0.__Instance;
            __Internal.cctor(__Instance, __arg0);
            SetupVTables(GetType().FullName == "NWN.LowLevel.CNWAmbientSound");
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::NWN.LowLevel.CNWAmbientSound __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            ((global::NWN.LowLevel.CNWAmbientSound.__Internal*) __Instance)->vptr_CNWAmbientSound = __VTables.Tables[0];
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public virtual void PlayMusic(int bPlay)
        {
            var ___PlayMusicDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 0);
            ___PlayMusicDelegate(__Instance, bPlay);
        }

        public virtual void SetMusicDelay(int nDelay)
        {
            var ___SetMusicDelayDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 1);
            ___SetMusicDelayDelegate(__Instance, nDelay);
        }

        public virtual void SetMusicDayTrack(int nTrack)
        {
            var ___SetMusicDayTrackDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 2);
            ___SetMusicDayTrackDelegate(__Instance, nTrack);
        }

        public virtual void SetMusicNightTrack(int nTrack)
        {
            var ___SetMusicNightTrackDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 3);
            ___SetMusicNightTrackDelegate(__Instance, nTrack);
        }

        public virtual void PlayBattleMusic(int bPlay)
        {
            var ___PlayBattleMusicDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 4);
            ___PlayBattleMusicDelegate(__Instance, bPlay);
        }

        public virtual void SetBattleMusicTrack(int nTrack)
        {
            var ___SetBattleMusicTrackDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 5);
            ___SetBattleMusicTrackDelegate(__Instance, nTrack);
        }

        public virtual void PlayAmbientSound(int bPlay)
        {
            var ___PlayAmbientSoundDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 6);
            ___PlayAmbientSoundDelegate(__Instance, bPlay);
        }

        public virtual void SetAmbientDayTrack(int nTrack)
        {
            var ___SetAmbientDayTrackDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 7);
            ___SetAmbientDayTrackDelegate(__Instance, nTrack);
        }

        public virtual void SetAmbientNightTrack(int nTrack)
        {
            var ___SetAmbientNightTrackDelegate = __VTables.GetMethodDelegate<global::NWN.LowLevel.Delegates.Action___IntPtr_int>(0, 8);
            ___SetAmbientNightTrackDelegate(__Instance, nTrack);
        }

        public int MBMusicPlaying
        {
            get
            {
                return ((__Internal*)__Instance)->m_bMusicPlaying;
            }

            set
            {
                ((__Internal*)__Instance)->m_bMusicPlaying = value;
            }
        }

        public int MNMusicDelay
        {
            get
            {
                return ((__Internal*)__Instance)->m_nMusicDelay;
            }

            set
            {
                ((__Internal*)__Instance)->m_nMusicDelay = value;
            }
        }

        public int MNMusicDayTrack
        {
            get
            {
                return ((__Internal*)__Instance)->m_nMusicDayTrack;
            }

            set
            {
                ((__Internal*)__Instance)->m_nMusicDayTrack = value;
            }
        }

        public int MNMusicNightTrack
        {
            get
            {
                return ((__Internal*)__Instance)->m_nMusicNightTrack;
            }

            set
            {
                ((__Internal*)__Instance)->m_nMusicNightTrack = value;
            }
        }

        public int MBBattlePlaying
        {
            get
            {
                return ((__Internal*)__Instance)->m_bBattlePlaying;
            }

            set
            {
                ((__Internal*)__Instance)->m_bBattlePlaying = value;
            }
        }

        public int MNBattleTrack
        {
            get
            {
                return ((__Internal*)__Instance)->m_nBattleTrack;
            }

            set
            {
                ((__Internal*)__Instance)->m_nBattleTrack = value;
            }
        }

        public int MBSoundPlaying
        {
            get
            {
                return ((__Internal*)__Instance)->m_bSoundPlaying;
            }

            set
            {
                ((__Internal*)__Instance)->m_bSoundPlaying = value;
            }
        }

        public int MNSoundDayTrack
        {
            get
            {
                return ((__Internal*)__Instance)->m_nSoundDayTrack;
            }

            set
            {
                ((__Internal*)__Instance)->m_nSoundDayTrack = value;
            }
        }

        public int MNSoundNightTrack
        {
            get
            {
                return ((__Internal*)__Instance)->m_nSoundNightTrack;
            }

            set
            {
                ((__Internal*)__Instance)->m_nSoundNightTrack = value;
            }
        }

        public byte MNDayVolume
        {
            get
            {
                return ((__Internal*)__Instance)->m_nDayVolume;
            }

            set
            {
                ((__Internal*)__Instance)->m_nDayVolume = value;
            }
        }

        public byte MNNightVolume
        {
            get
            {
                return ((__Internal*)__Instance)->m_nNightVolume;
            }

            set
            {
                ((__Internal*)__Instance)->m_nNightVolume = value;
            }
        }

        #region Virtual table interop

        // void PlayMusic(BOOL bPlay)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _PlayMusicDelegateInstance;

        private static void _PlayMusicDelegateHook(__IntPtr __instance, int bPlay)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.PlayMusic(bPlay);
        }

        // void SetMusicDelay(int32_t nDelay)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetMusicDelayDelegateInstance;

        private static void _SetMusicDelayDelegateHook(__IntPtr __instance, int nDelay)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetMusicDelay(nDelay);
        }

        // void SetMusicDayTrack(int32_t nTrack)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetMusicDayTrackDelegateInstance;

        private static void _SetMusicDayTrackDelegateHook(__IntPtr __instance, int nTrack)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetMusicDayTrack(nTrack);
        }

        // void SetMusicNightTrack(int32_t nTrack)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetMusicNightTrackDelegateInstance;

        private static void _SetMusicNightTrackDelegateHook(__IntPtr __instance, int nTrack)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetMusicNightTrack(nTrack);
        }

        // void PlayBattleMusic(BOOL bPlay)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _PlayBattleMusicDelegateInstance;

        private static void _PlayBattleMusicDelegateHook(__IntPtr __instance, int bPlay)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.PlayBattleMusic(bPlay);
        }

        // void SetBattleMusicTrack(int32_t nTrack)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetBattleMusicTrackDelegateInstance;

        private static void _SetBattleMusicTrackDelegateHook(__IntPtr __instance, int nTrack)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetBattleMusicTrack(nTrack);
        }

        // void PlayAmbientSound(BOOL bPlay)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _PlayAmbientSoundDelegateInstance;

        private static void _PlayAmbientSoundDelegateHook(__IntPtr __instance, int bPlay)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.PlayAmbientSound(bPlay);
        }

        // void SetAmbientDayTrack(int32_t nTrack)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetAmbientDayTrackDelegateInstance;

        private static void _SetAmbientDayTrackDelegateHook(__IntPtr __instance, int nTrack)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetAmbientDayTrack(nTrack);
        }

        // void SetAmbientNightTrack(int32_t nTrack)
        private static global::NWN.LowLevel.Delegates.Action___IntPtr_int _SetAmbientNightTrackDelegateInstance;

        private static void _SetAmbientNightTrackDelegateHook(__IntPtr __instance, int nTrack)
        {
            var __target = global::NWN.LowLevel.CNWAmbientSound.__GetInstance(__instance);
            __target.SetAmbientNightTrack(nTrack);
        }

        internal static class VTableLoader
        {
            private static volatile bool initialized;
            private static readonly IntPtr*[] ManagedVTables = new IntPtr*[1];
            private static readonly IntPtr[] Thunks = new IntPtr[9];
            private static CppSharp.Runtime.VTables VTables;
            private static readonly global::System.Collections.Generic.List<CppSharp.Runtime.SafeUnmanagedMemoryHandle>
                SafeHandles = new global::System.Collections.Generic.List<CppSharp.Runtime.SafeUnmanagedMemoryHandle>();

            static VTableLoader()
            {
                _PlayMusicDelegateInstance += _PlayMusicDelegateHook;
                _SetMusicDelayDelegateInstance += _SetMusicDelayDelegateHook;
                _SetMusicDayTrackDelegateInstance += _SetMusicDayTrackDelegateHook;
                _SetMusicNightTrackDelegateInstance += _SetMusicNightTrackDelegateHook;
                _PlayBattleMusicDelegateInstance += _PlayBattleMusicDelegateHook;
                _SetBattleMusicTrackDelegateInstance += _SetBattleMusicTrackDelegateHook;
                _PlayAmbientSoundDelegateInstance += _PlayAmbientSoundDelegateHook;
                _SetAmbientDayTrackDelegateInstance += _SetAmbientDayTrackDelegateHook;
                _SetAmbientNightTrackDelegateInstance += _SetAmbientNightTrackDelegateHook;
                Thunks[0] = Marshal.GetFunctionPointerForDelegate(_PlayMusicDelegateInstance);
                Thunks[1] = Marshal.GetFunctionPointerForDelegate(_SetMusicDelayDelegateInstance);
                Thunks[2] = Marshal.GetFunctionPointerForDelegate(_SetMusicDayTrackDelegateInstance);
                Thunks[3] = Marshal.GetFunctionPointerForDelegate(_SetMusicNightTrackDelegateInstance);
                Thunks[4] = Marshal.GetFunctionPointerForDelegate(_PlayBattleMusicDelegateInstance);
                Thunks[5] = Marshal.GetFunctionPointerForDelegate(_SetBattleMusicTrackDelegateInstance);
                Thunks[6] = Marshal.GetFunctionPointerForDelegate(_PlayAmbientSoundDelegateInstance);
                Thunks[7] = Marshal.GetFunctionPointerForDelegate(_SetAmbientDayTrackDelegateInstance);
                Thunks[8] = Marshal.GetFunctionPointerForDelegate(_SetAmbientNightTrackDelegateInstance);
            }

            public static CppSharp.Runtime.VTables SetupVTables(IntPtr instance, bool destructorOnly = false)
            {
                if (!initialized)
                {
                    lock (ManagedVTables)
                    {
                        if (!initialized)
                        {
                            initialized = true;
                            VTables.Tables = new IntPtr[] { *(IntPtr*)(instance + 0) };
                            VTables.Methods = new Delegate[1][];
                            ManagedVTables[0] = CppSharp.Runtime.VTables.CloneTable(SafeHandles, instance, 0, 11);
                            ManagedVTables[0][0] = Thunks[0];
                            ManagedVTables[0][1] = Thunks[1];
                            ManagedVTables[0][2] = Thunks[2];
                            ManagedVTables[0][3] = Thunks[3];
                            ManagedVTables[0][4] = Thunks[4];
                            ManagedVTables[0][5] = Thunks[5];
                            ManagedVTables[0][6] = Thunks[6];
                            ManagedVTables[0][7] = Thunks[7];
                            ManagedVTables[0][8] = Thunks[8];
                            VTables.Methods[0] = new Delegate[11];
                            if (destructorOnly)
                                return VTables;
                        }
                    }
                }

                *(IntPtr**)(instance + 0) = ManagedVTables[0];
                return VTables;
            }
        }

        protected CppSharp.Runtime.VTables __vtables;
        internal virtual CppSharp.Runtime.VTables __VTables
        { 
            get {
                if (__vtables.IsEmpty)
                    __vtables.Tables = new IntPtr[] { *(IntPtr*)(__Instance + 0) };
                return __vtables;
            }

            set {        
                __vtables = value;
            }
        }

        internal virtual void SetupVTables(bool destructorOnly = false)
        {
            if (__VTables.IsTransient)
                __VTables = VTableLoader.SetupVTables(__Instance, destructorOnly);
        }
        #endregion
    }
}

namespace Std
{
    namespace Pair
    {
        [StructLayout(LayoutKind.Explicit, Size = 80)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__S_CExoString___S_CNWSScriptVar
        {
            [FieldOffset(0)]
            internal global::NWN.LowLevel.CExoString.__Internal first;

            [FieldOffset(16)]
            internal global::NWN.LowLevel.CNWSScriptVar.__Internal second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C___S_CachedRulesetEntry
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::NWN.LowLevel.CachedRulesetEntry.__Internal second;
        }
    }

}
namespace Std
{
    namespace Hashtable
    {
        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S__Hashtable____S_CExoString___N_std_S_pair__1S0____S_CNWSScriptVar___N_std_S_allocator__S1____N_std_N___detail_S__Select1st___N_std_S_equal_to__S0____N_std_S_hash__S0____N_std_N___detail_S__Mod_range_hashing___N_std_N___detail_S__Default_ranged_hash___N_std_N___detail_S__Prime_rehash_policy___N_std_N___detail_S__Hashtable_traits__Vb1_Vb0_Vb1
        {
            [FieldOffset(0)]
            internal __IntPtr _M_buckets;

            [FieldOffset(8)]
            internal ulong _M_bucket_count;

            [FieldOffset(16)]
            internal global::Std.Detail.HashNodeBase.__Internal _M_before_begin;

            [FieldOffset(24)]
            internal ulong _M_element_count;

            [FieldOffset(32)]
            internal global::Std.Detail.PrimeRehashPolicy.__Internal _M_rehash_policy;

            [FieldOffset(48)]
            internal __IntPtr _M_single_bucket;
        }
    }
}
