// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

namespace NWN.LowLevel
{
    public unsafe partial class CResStructInternal : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 88)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::NWN.LowLevel.CResStructHeader.__Internal m_Header;

            [FieldOffset(8)]
            internal __IntPtr m_pLookUp;

            [FieldOffset(16)]
            internal __IntPtr m_pData;

            [FieldOffset(24)]
            internal uint m_nLocalDataSize;

            [FieldOffset(28)]
            internal uint m_nTotalDataSize;

            [FieldOffset(32)]
            internal uint m_nMaxDataSize;

            [FieldOffset(36)]
            internal uint m_nMaxLookUpID;

            [FieldOffset(40)]
            internal __IntPtr m_pParent;

            [FieldOffset(48)]
            internal uint m_nParentIndex;

            [FieldOffset(52)]
            internal int m_bIncludeStringHashTable;

            [FieldOffset(56)]
            internal global::NWN.LowLevel.AurList.__Internal m_listStringFieldIDs;

            [FieldOffset(72)]
            internal int m_nNumEmptyFields;

            [FieldOffset(76)]
            internal int m_nNumCopiedFields;

            [FieldOffset(80)]
            internal __IntPtr m_pChildList;

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN18CResStructInternalC2Ej", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void ctor(__IntPtr __instance, uint nType);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN18CResStructInternalC2ERS_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void cctor(__IntPtr __instance, __IntPtr _0);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN18CResStructInternalD2Ev", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void dtor(__IntPtr __instance);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN18CResStructInternal19WriteSideHashSearchEPc", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern uint WriteSideHashSearch(__IntPtr __instance, sbyte* szFieldID);

            [SuppressUnmanagedCodeSecurity, DllImport("NWNXLib", EntryPoint = "_ZN18CResStructInternal19HashSortStringTableEP7AurListIP16CResStructLookUpEPS0_IP18CStringFieldIDTypeE", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void HashSortStringTable(__IntPtr __instance, __IntPtr pOutputLookupPointers, __IntPtr pOutputFieldIDPointers);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CResStructInternal> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::NWN.LowLevel.CResStructInternal>();

        protected bool __ownsNativeInstance;

        internal static CResStructInternal __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            return new CResStructInternal(native.ToPointer(), skipVTables);
        }

        internal static CResStructInternal __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (NativeToManagedMap.TryGetValue(native, out var managed))
                return (CResStructInternal)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                NativeToManagedMap[native] = result;
            return result;
        }

        internal static CResStructInternal __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new CResStructInternal(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            global::NWN.LowLevel.CResStructInternal.__Internal.cctor(ret, new __IntPtr(&native));
            return ret.ToPointer();
        }

        private CResStructInternal(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected CResStructInternal(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        public CResStructInternal(uint nType)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CResStructInternal.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor(__Instance, nType);
        }

        public CResStructInternal(global::NWN.LowLevel.CResStructInternal _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::NWN.LowLevel.CResStructInternal.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(_0, null))
                throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = _0.__Instance;
            __Internal.cctor(__Instance, __arg0);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::NWN.LowLevel.CResStructInternal __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (disposing)
                __Internal.dtor(__Instance);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public uint WriteSideHashSearch(sbyte* szFieldID)
        {
            var __ret = __Internal.WriteSideHashSearch(__Instance, szFieldID);
            return __ret;
        }

        public void HashSortStringTable(global::NWN.LowLevel.AurList<global::NWN.LowLevel.CResStructLookUp> pOutputLookupPointers, global::NWN.LowLevel.AurList<global::NWN.LowLevel.CStringFieldIDType> pOutputFieldIDPointers)
        {
            var __arg0 = pOutputLookupPointers is null ? __IntPtr.Zero : pOutputLookupPointers.__Instance;
            var __arg1 = pOutputFieldIDPointers is null ? __IntPtr.Zero : pOutputFieldIDPointers.__Instance;
            __Internal.HashSortStringTable(__Instance, __arg0, __arg1);
        }

        public static implicit operator global::NWN.LowLevel.CResStructInternal(uint nType)
        {
            return new global::NWN.LowLevel.CResStructInternal(nType);
        }

        public global::NWN.LowLevel.CResStructHeader MHeader
        {
            get
            {
                return global::NWN.LowLevel.CResStructHeader.__CreateInstance(new __IntPtr(&((__Internal*)__Instance)->m_Header));
            }

            set
            {
                if (ReferenceEquals(value, null))
                    throw new global::System.ArgumentNullException("value", "Cannot be null because it is passed by value.");
                ((__Internal*)__Instance)->m_Header = *(global::NWN.LowLevel.CResStructHeader.__Internal*) value.__Instance;
            }
        }

        public global::NWN.LowLevel.CResStructLookUp MPLookUp
        {
            get
            {
                var __result0 = global::NWN.LowLevel.CResStructLookUp.__GetOrCreateInstance(((__Internal*)__Instance)->m_pLookUp, false);
                return __result0;
            }

            set
            {
                ((__Internal*)__Instance)->m_pLookUp = value is null ? __IntPtr.Zero : value.__Instance;
            }
        }

        public __IntPtr MPData
        {
            get
            {
                return ((__Internal*)__Instance)->m_pData;
            }

            set
            {
                ((__Internal*)__Instance)->m_pData = (__IntPtr) value;
            }
        }

        public uint MNLocalDataSize
        {
            get
            {
                return ((__Internal*)__Instance)->m_nLocalDataSize;
            }

            set
            {
                ((__Internal*)__Instance)->m_nLocalDataSize = value;
            }
        }

        public uint MNTotalDataSize
        {
            get
            {
                return ((__Internal*)__Instance)->m_nTotalDataSize;
            }

            set
            {
                ((__Internal*)__Instance)->m_nTotalDataSize = value;
            }
        }

        public uint MNMaxDataSize
        {
            get
            {
                return ((__Internal*)__Instance)->m_nMaxDataSize;
            }

            set
            {
                ((__Internal*)__Instance)->m_nMaxDataSize = value;
            }
        }

        public uint MNMaxLookUpID
        {
            get
            {
                return ((__Internal*)__Instance)->m_nMaxLookUpID;
            }

            set
            {
                ((__Internal*)__Instance)->m_nMaxLookUpID = value;
            }
        }

        public global::NWN.LowLevel.CResStructInternal MPParent
        {
            get
            {
                var __result0 = global::NWN.LowLevel.CResStructInternal.__GetOrCreateInstance(((__Internal*)__Instance)->m_pParent, false);
                return __result0;
            }

            set
            {
                ((__Internal*)__Instance)->m_pParent = value is null ? __IntPtr.Zero : value.__Instance;
            }
        }

        public uint MNParentIndex
        {
            get
            {
                return ((__Internal*)__Instance)->m_nParentIndex;
            }

            set
            {
                ((__Internal*)__Instance)->m_nParentIndex = value;
            }
        }

        public int MBIncludeStringHashTable
        {
            get
            {
                return ((__Internal*)__Instance)->m_bIncludeStringHashTable;
            }

            set
            {
                ((__Internal*)__Instance)->m_bIncludeStringHashTable = value;
            }
        }

        public global::NWN.LowLevel.AurList<global::NWN.LowLevel.CStringFieldIDType> MListStringFieldIDs
        {
            get
            {
                return global::NWN.LowLevel.AurList<global::NWN.LowLevel.CStringFieldIDType>.__CreateInstance(new __IntPtr(&((__Internal*)__Instance)->m_listStringFieldIDs));
            }

            set
            {
                if (ReferenceEquals(value, null))
                    throw new global::System.ArgumentNullException("value", "Cannot be null because it is passed by value.");
                ((__Internal*)__Instance)->m_listStringFieldIDs = *(global::NWN.LowLevel.AurList.__Internal*) value.__Instance;
            }
        }

        public int MNNumEmptyFields
        {
            get
            {
                return ((__Internal*)__Instance)->m_nNumEmptyFields;
            }

            set
            {
                ((__Internal*)__Instance)->m_nNumEmptyFields = value;
            }
        }

        public int MNNumCopiedFields
        {
            get
            {
                return ((__Internal*)__Instance)->m_nNumCopiedFields;
            }

            set
            {
                ((__Internal*)__Instance)->m_nNumCopiedFields = value;
            }
        }
    }
}

namespace Std
{
    namespace Pair
    {
        [StructLayout(LayoutKind.Explicit, Size = 80)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__S_CExoString___S_CNWSScriptVar
        {
            [FieldOffset(0)]
            internal global::NWN.LowLevel.CExoString.__Internal first;

            [FieldOffset(16)]
            internal global::NWN.LowLevel.CNWSScriptVar.__Internal second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C___S_CachedRulesetEntry
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_N___cxx11_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::NWN.LowLevel.CachedRulesetEntry.__Internal second;
        }
    }

}
namespace Std
{
    namespace Hashtable
    {
        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public unsafe partial struct __Internalc__N_std_S__Hashtable____S_CExoString___N_std_S_pair__1S0____S_CNWSScriptVar___N_std_S_allocator__S1____N_std_N___detail_S__Select1st___N_std_S_equal_to__S0____N_std_S_hash__S0____N_std_N___detail_S__Mod_range_hashing___N_std_N___detail_S__Default_ranged_hash___N_std_N___detail_S__Prime_rehash_policy___N_std_N___detail_S__Hashtable_traits__Vb1_Vb0_Vb1
        {
            [FieldOffset(0)]
            internal __IntPtr _M_buckets;

            [FieldOffset(8)]
            internal ulong _M_bucket_count;

            [FieldOffset(16)]
            internal global::Std.Detail.HashNodeBase.__Internal _M_before_begin;

            [FieldOffset(24)]
            internal ulong _M_element_count;

            [FieldOffset(32)]
            internal global::Std.Detail.PrimeRehashPolicy.__Internal _M_rehash_policy;

            [FieldOffset(48)]
            internal __IntPtr _M_single_bucket;
        }
    }
}
